site_name: Internal Assistant
site_description: Private, secure, customizable GenAI development framework
site_author: Internal Assistant Team
site_url: https://gitsolved.github.io/Internal-Banking-Assistant

# Repository
repo_name: GitSolved/Internal-Banking-Assistant
repo_url: https://github.com/GitSolved/Internal-Banking-Assistant
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

# Navigation
nav:
  - Home: index.md
  - User Guide:
    - Installation:
      - Main Concepts: user/installation/concepts.md
      - Installation Guide: user/installation/installation.md
      - Troubleshooting: user/installation/troubleshooting.md
    - Configuration:
      - Settings: user/configuration/settings.md
      - LLMs: user/configuration/llms.md
    - Usage:
      - Quickstart: user/usage/quickstart.md
      - Ingestion: user/usage/ingestion.md
      - Ingestion Reset: user/usage/ingestion-reset.md
      - Summarize: user/usage/summarize.md
  # Migration Plan: MIGRATION_PLAN.md (removed - migration completed)
  - Compatibility Guide: compatibility/compatibility_guide.md
  - API Reference:
    - Overview: api/reference/api-reference.md
  - Developer:
    - Architecture:
      - Overview: developer/architecture/overview.md
      - Data Lifecycle: developer/architecture/data-lifecycle.md
    - Development:
      - Setup: developer/development/setup.md
      - Package Structure: developer/development/package-structure.md
      - Documentation Guidelines: developer/development/documentation-guidelines.md

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      enable_git_follow: false

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JS
# extra_css:
#   - stylesheets/extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6

# Copyright
copyright: Copyright &copy; 2024 Internal Assistant Team
