# Internal Assistant Docker Compose Configuration
# 
# DEPENDENCY COMPATIBILITY NOTICE:
# This Docker setup requires specific dependency versions to ensure compatibility:
# - FastAPI: >=0.108.0,<0.115.0 (avoids Pydantic schema generation issues)
# - Pydantic: >=2.8.0,<2.9.0 (compatible with LlamaIndex)
# - Gradio: >=4.15.0,<4.39.0 (avoids FastAPI integration issues)
# - Python: 3.11.9 (required for all dependencies)
#
# These versions are enforced in the Dockerfile and pyproject.toml

services:

  #-----------------------------------
  #---- Internal Assistant services -------
  #-----------------------------------

  # Internal Assistant service for the Ollama CPU and GPU modes
  # This service builds from an external Dockerfile and runs the Ollama mode.
  internal-assistant-ollama:
    image: ${PGPT_IMAGE:-internal-assistant}:${PGPT_TAG:-0.6.2}-ollama  # x-release-please-version
    user: root
    build:
      context: ../../..
      dockerfile: config/deployment/docker/Dockerfile.ollama
    volumes:
      - ../../../local_data:/home/worker/app/local_data
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      PGPT_PROFILES: docker
      PGPT_MODE: ollama
      PGPT_EMBED_MODE: ollama
      PGPT_OLLAMA_API_BASE: http://ollama:11434
      HF_TOKEN: ${HF_TOKEN:-}
      GRADIO_ANALYTICS_ENABLED: "False"
    profiles:
      - ""
      - ollama-cpu
      - ollama-cuda
      - ollama-api
    depends_on:
      ollama:
        condition: service_healthy

  # Internal Assistant service for the local mode
  # This service builds from a local Dockerfile and runs the application in local mode.
  internal-assistant-llamacpp-cpu:
    image: ${PGPT_IMAGE:-internal-assistant}:${PGPT_TAG:-0.6.2}-llamacpp-cpu # x-release-please-version
    user: root
    build:
      context: ../../..
      dockerfile: config/deployment/docker/Dockerfile.llamacpp-cpu
    volumes:
      - ../../../local_data/:/home/worker/app/local_data
      - ../../../models/:/home/worker/app/models
    entrypoint: sh -c ".venv/bin/python -m internal_assistant"
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      PGPT_PROFILES: local
      HF_TOKEN: ${HF_TOKEN:-}
      GRADIO_ANALYTICS_ENABLED: "False"
    profiles:
      - llamacpp-cpu

  #-----------------------------------
  #---- Ollama services --------------
  #-----------------------------------

  # Traefik reverse proxy for the Ollama service
  # This will route requests to the Ollama service based on the profile.
  ollama:
    image: traefik:v2.10
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -q --spider http://ollama:11434 || exit 1"]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s
    ports:
      - "8080:8080"
    command:
      - "--providers.file.filename=/etc/router.yml"
      - "--log.level=ERROR"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:11434"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.docker/router.yml:/etc/router.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles:
      - ""
      - ollama-cpu
      - ollama-cuda
      - ollama-api

  # Ollama service for the CPU mode
  ollama-cpu:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ../../../models:/root/.ollama
    profiles:
      - ""
      - ollama-cpu

  # Ollama service for the CUDA mode
  ollama-cuda:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ../../../models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - ollama-cuda
