server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8080}

llm:
  mode: ${PGPT_MODE:ollama}
  prompt_style: "foundation-sec"
  max_new_tokens: 1000
  context_window: 8192
  temperature: 0.1

embedding:
  mode: ${PGPT_EMBED_MODE:huggingface}
  embed_dim: 768

vectorstore:
  database: qdrant

qdrant:
  path: local_data/internal_assistant/qdrant

rag:
  similarity_top_k: 8
  similarity_value: 0.1
  rerank:
    enabled: false

llamacpp:
  llm_hf_repo_id: ${PGPT_HF_REPO_ID:local/Foundation-Sec-8B}
  llm_hf_model_file: ${PGPT_HF_MODEL_FILE:Foundation-Sec-8B-q4_k_m.gguf}

huggingface:
  embedding_hf_model_name: ${PGPT_EMBEDDING_HF_MODEL_NAME:nomic-ai/nomic-embed-text-v1.5}

sagemaker:
  llm_endpoint_name: ${PGPT_SAGEMAKER_LLM_ENDPOINT_NAME:}
  embedding_endpoint_name: ${PGPT_SAGEMAKER_EMBEDDING_ENDPOINT_NAME:}

ollama:
  llm_model: ${PGPT_OLLAMA_LLM_MODEL:foundation-sec-q4km:latest}
  embedding_model: ${PGPT_OLLAMA_EMBEDDING_MODEL:nomic-embed-text}
  api_base: ${PGPT_OLLAMA_API_BASE:http://ollama:11434}
  embedding_api_base: ${PGPT_OLLAMA_EMBEDDING_API_BASE:http://ollama:11434}
  tfs_z: ${PGPT_OLLAMA_TFS_Z:1.0}
  top_k: ${PGPT_OLLAMA_TOP_K:40}
  top_p: ${PGPT_OLLAMA_TOP_P:0.9}
  repeat_last_n: ${PGPT_OLLAMA_REPEAT_LAST_N:64}
  repeat_penalty: ${PGPT_OLLAMA_REPEAT_PENALTY:1.1}
  request_timeout: ${PGPT_OLLAMA_REQUEST_TIMEOUT:120.0}
  autopull_models: ${PGPT_OLLAMA_AUTOPULL_MODELS:true}

ui:
  enabled: true
  path: /
